import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from database import engine
from etl_pipeline import run_pipeline
from risk_engine import load_returns, analyze_portfolio
from llm_analyst import generate_risk_briefing

# ---------------- PAGE CONFIGURATION ----------------
st.set_page_config(
    page_title="Quantitative Portfolio Risk & Allocation Engine",
    page_icon="📈",
    layout="wide",
)

st.title("📈 Quantitative Portfolio Risk & Allocation Engine")
st.caption("Production Data Pipeline, Mean-Variance Optimization, and GenAI Risk Analysis")

# ---------------- SIDEBAR CONTROLS ----------------
st.sidebar.header("⚙️ Engine Configuration")

# Pipeline Trigger
if st.sidebar.button("🔄 Run ETL Data Pipeline", use_container_width=True):
    with st.spinner("Ingesting market feeds and writing to SQL database..."):
        try:
            records = run_pipeline()
            st.sidebar.success(f"Pipeline executed: {records} rows processed.")
        except Exception as e:
            st.sidebar.error(f"Pipeline failure: {e}")

# Gemini API Key Setup
st.sidebar.markdown("---")
st.sidebar.subheader("🤖 GenAI Risk Analyst")
api_key = st.sidebar.text_input(
    "Enter Gemini API Key",
    type="password",
    help="Enter your Google AI Studio API key to activate executive briefings."
)

# ---------------- MAIN DATA & RISK ANALYSIS ----------------
try:
    returns_df = load_returns(engine)
except Exception as e:
    st.error(f"Could not load asset returns from the database. Run the ETL pipeline first: {e}")
    st.stop()

if returns_df.empty:
    st.warning("Database contains no return data. Please click 'Run ETL Data Pipeline' in the sidebar.")
    st.stop()

# Run quantitative risk analysis
report = analyze_portfolio(returns_df)

# ---------------- ROW 1: CORE RISK METRICS ----------------
st.subheader("📊 Key Risk & Return Metrics")
m1, m2, m3, m4, m5 = st.columns(5)

exp_ret = report.get("expected_annual_return", report.get("expected_return", 0) * 100)
vol = report.get("annual_volatility_risk", report.get("volatility", 0) * 100)
sharpe = report.get("max_sharpe", report.get("sharpe_ratio", 0))
var95 = report.get("var_95_daily_pct", report.get("var_95", 0) * 100)
mdd = report.get("max_drawdown_pct", report.get("max_drawdown", 0) * 100)

m1.metric("Expected Return", f"{exp_ret:.2f}%")
m2.metric("Annual Volatility", f"{vol:.2f}%")
m3.metric("Max Sharpe Ratio", f"{sharpe:.2f}")
m4.metric("1-Day 95% VaR", f"{var95:.2f}%")
m5.metric("Max Drawdown", f"{mdd:.2f}%")

st.divider()

# ---------------- ROW 2: ALLOCATION & CHARTS ----------------
c1, c2 = st.columns(2)

with c1:
    st.subheader("🎯 Optimal Asset Allocation")
    weights = report.get("optimal_weights", {})
    if weights:
        weights_df = pd.DataFrame(list(weights.items()), columns=["Asset", "Weight"])
        fig_pie = px.pie(
            weights_df,
            names="Asset",
            values="Weight",
            hole=0.4,
            color_discrete_sequence=px.colors.qualitative.Prism,
        )
        fig_pie.update_layout(margin=dict(t=20, b=20, l=20, r=20))
        st.plotly_chart(fig_pie, use_container_width=True)
    else:
        st.info("No optimal weights computed.")

with c2:
    st.subheader("📉 Historical Asset Cumulative Returns")
    cumulative_returns = (1 + returns_df).cumprod()
    fig_line = px.line(
        cumulative_returns,
        labels={"value": "Growth ($1 Base)", "Date": "Timeline"},
        color_discrete_sequence=px.colors.qualitative.Safe,
    )
    fig_line.update_layout(
        legend_title_text="Ticker",
        margin=dict(t=20, b=20, l=20, r=20)
    )
    st.plotly_chart(fig_line, use_container_width=True)

st.divider()

# ---------------- ROW 3: GENAI EXECUTIVE BRIEFING ----------------
st.subheader("🤖 Executive AI Risk Committee Briefing")
st.caption("Synthesized quantitative intelligence generated by Gemini 3.6 Flash reasoning.")

if st.button("Generate AI Risk Committee Briefing", type="primary"):
    if not api_key:
        st.warning("⚠️ Please provide a Gemini API Key in the sidebar first.")
    else:
        with st.spinner("Analyzing risk metrics and formulating executive notes..."):
            try:
                briefing_text = generate_risk_briefing(report, api_key)
                st.success("Executive Briefing Successfully Generated!")
                st.markdown(briefing_text)
            except Exception as e:
                st.error(f"Error generating briefing: {e}")

st.divider()

# ---------------- ROW 4: DATA ENGINEERING EXPLORER ----------------
with st.expander("🔍 View Raw Database Historical Log & Model Schema"):
    st.dataframe(returns_df.tail(25), use_container_width=True)